import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { NextIntlClientProvider } from 'next-intl';
import { AiToolsClient } from './ai-tools-client';

const messages = {
  aiPage: {
    kicker: 'AI',
    title: 'AI Tools',
    description:
      'Generate content suggestions using artificial intelligence (demo — not connected to a live AI model)',
    demoBadge: 'Demo',
    demoNotice:
      'This feature is a preview. Suggestions are sample data, not generated by a live AI model.',
    tool_headline: 'Headline Generator',
    tool_headline_desc: 'Generate catchy headlines for your displays',
    'tool_body-text': 'Body Text Writer',
    'tool_body-text_desc': 'Write engaging body text for your content',
    tool_cta: 'CTA Generator',
    tool_cta_desc: 'Create compelling call-to-action messages',
    'tool_color-scheme': 'Color Scheme Advisor',
    'tool_color-scheme_desc': 'Get color palette suggestions for your industry',
    generate: 'Generate',
    generating: 'Generating...',
    usage: 'Usage Statistics',
    usageDemoNotice: 'Usage statistics are illustrative only.',
    historyTitle: 'Suggestion History',
    clearHistory: 'Clear',
  },
};

function renderAiTools() {
  return render(
    <NextIntlClientProvider locale="en" messages={messages}>
      <AiToolsClient />
    </NextIntlClientProvider>,
  );
}

describe('AiToolsClient (T4.3 — demo labeling)', () => {
  it('renders a visible Demo badge', () => {
    renderAiTools();
    expect(screen.getByText('Demo')).toBeInTheDocument();
  });

  it('renders the demo notice explaining suggestions are sample data', () => {
    renderAiTools();
    expect(
      screen.getAllByText(
        'This feature is a preview. Suggestions are sample data, not generated by a live AI model.',
      ).length,
    ).toBeGreaterThan(0);
  });

  it('renders the usage demo notice instead of fake numbers', () => {
    const { container } = renderAiTools();
    expect(container.textContent).toContain(
      'Usage statistics are illustrative only.',
    );
  });

  it('does not render fake total requests count (142)', () => {
    const { container } = renderAiTools();
    expect(container.textContent).not.toContain('142');
  });

  it('does not render fake spend amount ($3.27)', () => {
    const { container } = renderAiTools();
    expect(container.textContent).not.toContain('3.27');
  });
});
