import type { CanvasLayoutV1, CanvasObjectJson } from './canvas-layout';

export type CanvasTemplate = {
  id: string;
  name: string;
  nameAr: string;
  width: number;
  height: number;
  layout: CanvasLayoutV1;
};

function uid(): string {
  return crypto.randomUUID();
}

export const CANVAS_TEMPLATES: CanvasTemplate[] = [
  {
    id: 'blank-landscape',
    name: 'Blank Landscape',
    nameAr: 'فارغ أفقي',
    width: 1920,
    height: 1080,
    layout: { version: 1, objects: [] },
  },
  {
    id: 'blank-portrait',
    name: 'Blank Portrait',
    nameAr: 'فارغ عمودي',
    width: 1080,
    height: 1920,
    layout: { version: 1, objects: [] },
  },
  {
    id: 'welcome-screen',
    name: 'Welcome Screen',
    nameAr: 'شاشة ترحيب',
    width: 1920,
    height: 1080,
    layout: {
      version: 1,
      objects: [
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: '#0f172a',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 210,
          y: 380,
          text: 'Welcome',
          fontSize: 120,
          fill: '#ffffff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 310,
          y: 540,
          text: 'to our store',
          fontSize: 48,
          fill: '#94a3b8',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
      ],
    },
  },
  {
    id: 'promo-sale',
    name: 'Promo / Sale',
    nameAr: 'عرض ترويجي',
    width: 1920,
    height: 1080,
    layout: {
      version: 1,
      objects: [
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: '#dc2626',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 160,
          y: 300,
          text: '50% OFF',
          fontSize: 160,
          fill: '#ffffff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 360,
          y: 520,
          text: 'This weekend only',
          fontSize: 52,
          fill: '#fef2f2',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'rect',
          x: 660,
          y: 640,
          width: 600,
          height: 80,
          fill: '#ffffff',
          cornerRadius: 40,
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 760,
          y: 656,
          text: 'SHOP NOW',
          fontSize: 36,
          fill: '#dc2626',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
      ],
    },
  },
  {
    id: 'menu-board',
    name: 'Menu Board',
    nameAr: 'لوحة قائمة طعام',
    width: 1920,
    height: 1080,
    layout: {
      version: 1,
      objects: [
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: '#1c1917',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 120,
          fill: '#f59e0b',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 30,
          text: 'OUR MENU',
          fontSize: 56,
          fill: '#1c1917',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 120,
          y: 200,
          text: 'Coffee ................ $3.50',
          fontSize: 44,
          fill: '#fafaf9',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 120,
          y: 300,
          text: 'Tea ................... $2.50',
          fontSize: 44,
          fill: '#fafaf9',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 120,
          y: 400,
          text: 'Sandwich ............ $7.00',
          fontSize: 44,
          fill: '#fafaf9',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 120,
          y: 500,
          text: 'Salad ................. $8.50',
          fontSize: 44,
          fill: '#fafaf9',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
      ],
    },
  },
  {
    id: 'social-quote',
    name: 'Quote / Social',
    nameAr: 'اقتباس / سوشيال',
    width: 1080,
    height: 1080,
    layout: {
      version: 1,
      objects: [
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1080,
          height: 1080,
          fill: '#7c3aed',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 120,
          y: 360,
          text: '"The best way to predict the future is to create it"',
          fontSize: 56,
          fill: '#ffffff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'italic',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 320,
          y: 680,
          text: '— Peter Drucker',
          fontSize: 36,
          fill: '#e9d5ff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
      ],
    },
  },
  {
    id: 'split-two-zone',
    name: 'Split (2 Zones)',
    nameAr: 'تقسيم (منطقتان)',
    width: 1920,
    height: 1080,
    layout: {
      version: 1,
      objects: [
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 960,
          height: 1080,
          fill: '#0ea5e9',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'rect',
          x: 960,
          y: 0,
          width: 960,
          height: 1080,
          fill: '#0f172a',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 120,
          y: 460,
          text: 'Left Zone',
          fontSize: 64,
          fill: '#ffffff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 1100,
          y: 460,
          text: 'Right Zone',
          fontSize: 64,
          fill: '#ffffff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
      ],
    },
  },
];
