import type { CanvasLayoutV1, CanvasObjectJson } from './canvas-layout';

export type TemplateCategory =
  | 'business'
  | 'retail'
  | 'restaurant'
  | 'corporate'
  | 'education'
  | 'healthcare'
  | 'general';

export type CanvasTemplate = {
  id: string;
  name: string;
  nameAr: string;
  description: string;
  descriptionAr: string;
  category: TemplateCategory;
  orientation: 'landscape' | 'portrait' | 'square';
  usage: string;
  usageAr: string;
  width: number;
  height: number;
  layout: CanvasLayoutV1;
};

function uid(): string {
  return crypto.randomUUID();
}

export const CANVAS_TEMPLATES: CanvasTemplate[] = [
  {
    id: 'blank-landscape',
    name: 'Blank Landscape',
    nameAr: 'فارغ أفقي',
    description: 'Start from scratch with a blank landscape canvas.',
    descriptionAr: 'ابدأ من الصفر بلوحة فارغة أفقية.',
    category: 'general',
    orientation: 'landscape',
    usage: 'Custom designs requiring full creative freedom.',
    usageAr: 'تصاميم مخصصة تتطلب حرية إبداعية كاملة.',
    width: 1920,
    height: 1080,
    layout: { version: 1, objects: [] },
  },
  {
    id: 'blank-portrait',
    name: 'Blank Portrait',
    nameAr: 'فارغ عمودي',
    description: 'Start from scratch with a blank portrait canvas.',
    descriptionAr: 'ابدأ من الصفر بلوحة فارغة عمودية.',
    category: 'general',
    orientation: 'portrait',
    usage: 'Vertical displays, kiosks, and digital posters.',
    usageAr: 'الشاشات العمودية والأكشاك والملصقات الرقمية.',
    width: 1080,
    height: 1920,
    layout: { version: 1, objects: [] },
  },
  {
    id: 'welcome-screen',
    name: 'Welcome Screen',
    nameAr: 'شاشة ترحيب',
    description: 'Greet visitors with a bold welcome message on a dark backdrop.',
    descriptionAr: 'رحّب بزوارك برسالة ترحيب بارزة على خلفية داكنة.',
    category: 'corporate',
    orientation: 'landscape',
    usage: 'Lobbies, entrances, and reception areas.',
    usageAr: 'البهو والمداخل ومناطق الاستقبال.',
    width: 1920,
    height: 1080,
    layout: {
      version: 1,
      objects: [
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: '#0f172a',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 210,
          y: 380,
          text: 'Welcome',
          fontSize: 120,
          fill: '#ffffff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 310,
          y: 540,
          text: 'to our store',
          fontSize: 48,
          fill: '#94a3b8',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
      ],
    },
  },
  {
    id: 'promo-sale',
    name: 'Promo / Sale',
    nameAr: 'عرض ترويجي',
    description: 'Eye-catching promotional banner with discount and call-to-action.',
    descriptionAr: 'لافتة ترويجية جذابة مع خصم ودعوة للإجراء.',
    category: 'retail',
    orientation: 'landscape',
    usage: 'Retail stores, seasonal sales, and flash promotions.',
    usageAr: 'متاجر التجزئة والعروض الموسمية والتخفيضات السريعة.',
    width: 1920,
    height: 1080,
    layout: {
      version: 1,
      objects: [
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: '#dc2626',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 160,
          y: 300,
          text: '50% OFF',
          fontSize: 160,
          fill: '#ffffff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 360,
          y: 520,
          text: 'This weekend only',
          fontSize: 52,
          fill: '#fef2f2',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'rect',
          x: 660,
          y: 640,
          width: 600,
          height: 80,
          fill: '#ffffff',
          cornerRadius: 40,
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 760,
          y: 656,
          text: 'SHOP NOW',
          fontSize: 36,
          fill: '#dc2626',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
      ],
    },
  },
  {
    id: 'menu-board',
    name: 'Menu Board',
    nameAr: 'لوحة قائمة طعام',
    description: 'Professional menu board with header bar and itemized price list.',
    descriptionAr: 'لوحة قائمة احترافية مع شريط رأس وقائمة أسعار مفصّلة.',
    category: 'restaurant',
    orientation: 'landscape',
    usage: 'Restaurants, cafes, and food service displays.',
    usageAr: 'المطاعم والمقاهي وشاشات خدمات الطعام.',
    width: 1920,
    height: 1080,
    layout: {
      version: 1,
      objects: [
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: '#1c1917',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 120,
          fill: '#f59e0b',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 30,
          text: 'OUR MENU',
          fontSize: 56,
          fill: '#1c1917',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 120,
          y: 200,
          text: 'Coffee ................ $3.50',
          fontSize: 44,
          fill: '#fafaf9',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 120,
          y: 300,
          text: 'Tea ................... $2.50',
          fontSize: 44,
          fill: '#fafaf9',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 120,
          y: 400,
          text: 'Sandwich ............ $7.00',
          fontSize: 44,
          fill: '#fafaf9',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 120,
          y: 500,
          text: 'Salad ................. $8.50',
          fontSize: 44,
          fill: '#fafaf9',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
      ],
    },
  },
  {
    id: 'social-quote',
    name: 'Quote / Social',
    nameAr: 'اقتباس / سوشيال',
    description: 'Inspiring quote on a vibrant background for social media displays.',
    descriptionAr: 'اقتباس ملهم على خلفية نابضة لشاشات التواصل الاجتماعي.',
    category: 'general',
    orientation: 'square',
    usage: 'Social walls, waiting areas, and inspirational displays.',
    usageAr: 'جدران التواصل ومناطق الانتظار والشاشات الإلهامية.',
    width: 1080,
    height: 1080,
    layout: {
      version: 1,
      objects: [
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1080,
          height: 1080,
          fill: '#7c3aed',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 120,
          y: 360,
          text: '"The best way to predict the future is to create it"',
          fontSize: 56,
          fill: '#ffffff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'italic',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 320,
          y: 680,
          text: '— Peter Drucker',
          fontSize: 36,
          fill: '#e9d5ff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
      ],
    },
  },
  {
    id: 'split-two-zone',
    name: 'Split (2 Zones)',
    nameAr: 'تقسيم (منطقتان)',
    description: 'Two side-by-side content zones for dual-message displays.',
    descriptionAr: 'منطقتا محتوى جنباً إلى جنب لعرض رسالتين.',
    category: 'business',
    orientation: 'landscape',
    usage: 'Trade shows, comparison displays, and multi-content layouts.',
    usageAr: 'المعارض وعروض المقارنة وتخطيطات المحتوى المتعدد.',
    width: 1920,
    height: 1080,
    layout: {
      version: 1,
      objects: [
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 960,
          height: 1080,
          fill: '#0ea5e9',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'rect',
          x: 960,
          y: 0,
          width: 960,
          height: 1080,
          fill: '#0f172a',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 120,
          y: 460,
          text: 'Left Zone',
          fontSize: 64,
          fill: '#ffffff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 1100,
          y: 460,
          text: 'Right Zone',
          fontSize: 64,
          fill: '#ffffff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          align: 'center',
          opacity: 1,
        } as CanvasObjectJson,
      ],
    },
  },
  {
    id: 'announcement',
    name: 'Announcement',
    nameAr: 'إعلان',
    description: 'Bold announcement banner with title, message, and highlighted date strip.',
    descriptionAr: 'لافتة إعلان بارزة مع عنوان ورسالة وشريط تاريخ مميّز.',
    category: 'corporate',
    orientation: 'landscape',
    usage: 'Corporate lobbies, event notices, and internal communications.',
    usageAr: 'بهوات الشركات وإشعارات الأحداث والتواصل الداخلي.',
    width: 1920,
    height: 1080,
    layout: {
      version: 1,
      objects: [
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: '#1e3a8a',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 800,
          width: 1920,
          height: 80,
          fill: '#fbbf24',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 300,
          text: 'IMPORTANT',
          fontSize: 48,
          fill: '#93c5fd',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 380,
          text: 'Announcement',
          fontSize: 130,
          fill: '#ffffff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 560,
          text: 'Company-wide meeting this Friday at 2 PM',
          fontSize: 44,
          fill: '#bfdbfe',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 820,
          text: 'FRI · 2:00 PM · MAIN HALL',
          fontSize: 36,
          fill: '#1e3a8a',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          opacity: 1,
        } as CanvasObjectJson,
      ],
    },
  },
  {
    id: 'weather',
    name: 'Weather',
    nameAr: 'الطقس',
    description: 'Weather display with temperature, condition, and colored accent bar.',
    descriptionAr: 'عرض الطقس مع درجة الحرارة والحالة وشريط لوني مميّز.',
    category: 'general',
    orientation: 'landscape',
    usage: 'Hotel lobbies, transit hubs, and public information displays.',
    usageAr: 'بهوات الفنادق ومحاور النقل والشاشات المعلوماتية العامة.',
    width: 1920,
    height: 1080,
    layout: {
      version: 1,
      objects: [
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: '#0891b2',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 8,
          fill: '#67e8f9',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 200,
          text: 'Today',
          fontSize: 56,
          fill: '#a5f3fc',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 300,
          text: '24°',
          fontSize: 280,
          fill: '#ffffff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 660,
          text: 'Partly Cloudy',
          fontSize: 64,
          fill: '#e0f2fe',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 780,
          text: 'H: 28°  L: 18°  ·  Humidity 45%',
          fontSize: 40,
          fill: '#bae6fd',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
      ],
    },
  },
  {
    id: 'news',
    name: 'News',
    nameAr: 'الأخبار',
    description: 'News headline layout with category tag, headline, and summary text.',
    descriptionAr: 'تخطيط عناوين الأخبار مع تصنيف وعنوان رئيسي ونص ملخّص.',
    category: 'corporate',
    orientation: 'landscape',
    usage: 'Corporate communications, waiting rooms, and info channels.',
    usageAr: 'التواصل المؤسسي وغرف الانتظار والقنوات المعلوماتية.',
    width: 1920,
    height: 1080,
    layout: {
      version: 1,
      objects: [
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: '#0f172a',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 100,
          fill: '#ef4444',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 80,
          y: 20,
          text: 'BREAKING NEWS',
          fontSize: 48,
          fill: '#ffffff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 250,
          text: 'Major Update',
          fontSize: 100,
          fill: '#ffffff',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
          fontStyle: 'bold',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 400,
          text: 'New initiative launched to improve',
          fontSize: 56,
          fill: '#cbd5e1',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 480,
          text: 'workplace efficiency across all departments',
          fontSize: 56,
          fill: '#cbd5e1',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'rect',
          x: 100,
          y: 620,
          width: 120,
          height: 6,
          fill: '#ef4444',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 660,
          text: 'Read more details in the full report available on',
          fontSize: 36,
          fill: '#94a3b8',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
        {
          id: uid(),
          type: 'text',
          x: 100,
          y: 720,
          text: 'the company intranet portal.',
          fontSize: 36,
          fill: '#94a3b8',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif',
          opacity: 1,
        } as CanvasObjectJson,
      ],
    },
  },
];
